# Generated by Django 3.1.7 on 2021-04-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0002_auto_20210414_1542'),
        ('lead', '0009_auto_20210421_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4000, verbose_name='Text')),
                ('text_ru', models.CharField(max_length=4000, null=True, verbose_name='Text')),
                ('text_uz', models.CharField(max_length=4000, null=True, verbose_name='Text')),
                ('text_en', models.CharField(max_length=4000, null=True, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_photo', to='file.photo', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_location', to='lead.location', verbose_name='Location')),
            ],
        ),
    ]
