# Generated by Django 3.1.7 on 2021-05-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlocation',
            options={'verbose_name': 'Contact location', 'verbose_name_plural': 'Contact locations'},
        ),
        migrations.AlterModelOptions(
            name='contactphoto',
            options={'verbose_name': 'Contact photo', 'verbose_name_plural': 'Contact photos'},
        ),
        migrations.AlterModelOptions(
            name='contacttext',
            options={'verbose_name': 'Contact text', 'verbose_name_plural': 'Contact text'},
        ),
    ]
