# Generated by Django 3.1.7 on 2021-04-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproject',
            name='catalog_documents',
            field=models.ManyToManyField(related_name='document_commercial_projects', to='file.Document', verbose_name='Catalog documents'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='catalog_documents',
            field=models.ManyToManyField(related_name='document_residential_projects', to='file.Document', verbose_name='Catalog documents'),
        ),
    ]
