# Generated by Django 3.1.7 on 2021-04-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20210413_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description_en',
            field=models.CharField(max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_ru',
            field=models.CharField(max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_uz',
            field=models.CharField(max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='description_en',
            field=models.CharField(max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='description_ru',
            field=models.CharField(max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='description_uz',
            field=models.CharField(max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.CharField(max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.CharField(max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_uz',
            field=models.CharField(max_length=198, null=True, verbose_name='Description'),
        ),
    ]
