# Generated by Django 3.1.7 on 2021-04-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20210414_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproject',
            name='description_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='description_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='description_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='name_en',
            field=models.CharField(max_length=48, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='name_ru',
            field=models.CharField(max_length=48, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='name_uz',
            field=models.CharField(max_length=48, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='description_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='description_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='description_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='name_en',
            field=models.CharField(max_length=48, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='name_ru',
            field=models.CharField(max_length=48, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='name_uz',
            field=models.CharField(max_length=48, null=True, verbose_name='Name'),
        ),
    ]
