# Generated by Django 3.1.7 on 2021-04-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('lead', '0004_auto_20210414_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialproject',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='commercialproject',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='commercialproject',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='residentialproject',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='residentialproject',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='residentialproject',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commercialproject',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='commercial_projects', to='file.Document', verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='commercialproject',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='commercial_projects', to='file.Photo', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='commercialproject',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='commercial_projects', to='file.Video', verbose_name='Videos'),
        ),
        migrations.AlterField(
            model_name='residentialproject',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='residential_projects', to='file.Document', verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='residentialproject',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='residential_projects', to='file.Photo', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='residentialproject',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='residential_projects', to='file.Video', verbose_name='Videos'),
        ),
    ]
