# Generated by Django 3.1.7 on 2021-04-16 12:16

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_auto_20210414_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=core.utils.generate_number, verbose_name='Numver')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartments', models.ManyToManyField(related_name='leads', to='lead.Apartment', verbose_name='Apartments')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead.customer', verbose_name='Customer')),
                ('stores', models.ManyToManyField(related_name='leads', to='lead.Store', verbose_name='Stores')),
            ],
        ),
    ]
