# Generated by Django 3.1.7 on 2021-04-20 12:45

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='apartments',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='stores',
        ),
        migrations.AlterField(
            model_name='lead',
            name='number',
            field=models.IntegerField(default=core.utils.generate_number, verbose_name='Number'),
        ),
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_transactions', to='lead.customer', verbose_name='Customer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_transactions', to='lead.lead', verbose_name='Lead')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lead.store', verbose_name='Store')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lead.apartment', verbose_name='apartment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_transactions', to='lead.customer', verbose_name='Customer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_transactions', to='lead.lead', verbose_name='Lead')),
            ],
        ),
    ]
