# Generated by Django 3.1.7 on 2021-04-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20210414_1542'),
        ('lead', '0009_auto_20210421_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialproject',
            name='catalog_documents',
        ),
        migrations.RemoveField(
            model_name='residentialproject',
            name='catalog_documents',
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='catalogue_documents',
            field=models.ManyToManyField(related_name='catalogue_commercial_projects', to='file.Document', verbose_name='Catalog documents'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='catalogue_documents',
            field=models.ManyToManyField(related_name='catalogue_residential_projects', to='file.Document', verbose_name='Catalog documents'),
        ),
    ]
