# Generated by Django 3.1.7 on 2021-04-25 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_auto_20210423_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_quantity', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplexes', to='lead.residentialproject', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Floor number'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='lead.residentialproject', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Room quantity'),
        ),
        migrations.CreateModel(
            name='DuplexTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplex_transactions', to='lead.customer', verbose_name='Customer')),
                ('duplex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lead.duplex', verbose_name='Duplex')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplex_transactions', to='lead.lead', verbose_name='Lead')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='duplex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='lead.duplex', verbose_name='Duplex'),
        ),
    ]
