# Generated by Django 3.1.7 on 2021-04-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_auto_20210425_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialproject',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='residentialproject',
            name='videos',
        ),
    ]
