# Generated by Django 3.1.7 on 2021-05-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_auto_20210425_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterModelOptions(
            name='apartmenttransaction',
            options={'verbose_name': 'Apartment transaction', 'verbose_name_plural': 'Apartment transactions'},
        ),
        migrations.AlterModelOptions(
            name='commercialproject',
            options={'verbose_name': 'Commercial project', 'verbose_name_plural': 'Commercial projects'},
        ),
        migrations.AlterModelOptions(
            name='duplex',
            options={'verbose_name': 'Duplex', 'verbose_name_plural': 'Duplexes'},
        ),
        migrations.AlterModelOptions(
            name='duplextransaction',
            options={'verbose_name': 'Duplex transaction', 'verbose_name_plural': 'Duplex transactions'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-created_at',), 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='residentialproject',
            options={'verbose_name': 'Residential project', 'verbose_name_plural': 'Residential projects'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterModelOptions(
            name='storetransaction',
            options={'verbose_name': 'Store transaction', 'verbose_name_plural': 'Store transactions'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Floor number'),
        ),
    ]
