# Generated by Django 3.1.7 on 2021-06-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_auto_20210616_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='photos',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='photos',
            new_name='photo',
        ),
    ]
