# Generated by Django 3.1.7 on 2021-06-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_auto_20210616_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproject',
            name='about',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='about_en',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='about_ru',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='commercialproject',
            name='about_uz',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='about',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='about_en',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='about_ru',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='residentialproject',
            name='about_uz',
            field=models.CharField(max_length=4000, null=True, verbose_name='About project'),
        ),
    ]
