# Generated by Django 3.1.7 on 2021-04-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ru',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_uz',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_en',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_ru',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_uz',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_ru',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_uz',
            field=models.CharField(blank=True, max_length=198, null=True, verbose_name='Description'),
        ),
    ]
