# Generated by Django 3.1.7 on 2021-05-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20210414_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
