# Generated by Django 3.1.7 on 2021-04-23 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0002_auto_20210414_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4000, verbose_name='Text')),
                ('text_ru', models.CharField(max_length=4000, null=True, verbose_name='Text')),
                ('text_uz', models.CharField(max_length=4000, null=True, verbose_name='Text')),
                ('text_en', models.CharField(max_length=4000, null=True, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_uz', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='vacancy', to='file.photo', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_uz', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='service', to='file.photo', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_photo', to='file.photo', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_document', to='file.document', verbose_name='Document')),
            ],
        ),
    ]
