# Generated by Django 3.1.7 on 2021-04-25 06:49

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_auto_20210425_1149'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=core.utils.generate_number, verbose_name='Number')),
                ('cv_file_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_requests', to='lead.customer', verbose_name='Customer')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='company.vacancy', verbose_name='Vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=core.utils.generate_number, verbose_name='Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='lead.customer', verbose_name='Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='company.service', verbose_name='Service')),
            ],
        ),
    ]
