# Generated by Django 3.1.7 on 2021-05-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_servicerequest_vacancyrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydocument',
            options={'verbose_name': 'Company document', 'verbose_name_plural': 'Company documents'},
        ),
        migrations.AlterModelOptions(
            name='companyphoto',
            options={'verbose_name': 'Company photo', 'verbose_name_plural': 'company photos'},
        ),
        migrations.AlterModelOptions(
            name='companytext',
            options={'verbose_name': 'Company text', 'verbose_name_plural': 'Company text'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
