# Generated by Django 3.1.7 on 2021-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210522_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.CharField(max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.CharField(max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_uz',
            field=models.CharField(max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_en',
            field=models.CharField(max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_ru',
            field=models.CharField(max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_uz',
            field=models.CharField(max_length=3000, null=True, verbose_name='Description'),
        ),
    ]
